### ISSUE TITLE
Build infos missing

### ISSUE THREAD

**Issue by luchaos** [ixopay/pgc-woocommerce#1]
The README should provide information about requirements, how to build a branded extension from source and how to provide updates for the extension.

A build script should ease the process of building branded extensions from source.

**Comment by allsecure-pay** [comment]
Hi luchaos,

Thank you for getting in touch with us. 

We have received your message and will be responding to your enquiry as soon as possible.

-------------------------------------------------------------
Date: 2019-08-28
-------------------------------------------------------------
Name: luchaos
Email: reply@reply.github.com
Group: TECNICAL SUPPORT
-------------------------------------------------------------
The README should provide information about requirements, how to build a branded extension from source and how to provide updates for the extension.

A build script should ease the process of building branded extensions from source.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/ixopay/pgc-woocommerce/issues/1


Powered by LiveZilla Help Desk Software [https://www.livezilla.net]

Ticket History:
https://help.allsecpay.com/ticket.php?id=21143&hash=DBFEFDFB4DFD&salt=42e83c93525166efed8d50f7e91a17fa

[DBFEFDFB4DFD]

**Comment by allsecure-pay** [comment]
Hi luchaos,

Thank you for getting in touch with us. 

We have received your message and will be responding to your enquiry as soon as possible.

-------------------------------------------------------------
Date: 2019-08-30
-------------------------------------------------------------
Name: luchaos
Email: reply@reply.github.com
Group: TECNICAL SUPPORT
-------------------------------------------------------------
Closed #1 via 981ebba1b10fa20b81c83907c162c3e4e58ebb16.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/ixopay/pgc-woocommerce/issues/1#event-2597154519


Powered by LiveZilla Help Desk Software [https://www.livezilla.net]

Ticket History:
https://help.allsecpay.com/ticket.php?id=21155&hash=6DCC599E4E5E&salt=45ecfb69a88b604acd28137c360f43d2

[6DCC599E4E5E]
